// Questions
var q = [
	'What do you understand that others don&#39;t?',
	'Why will you succeed?',
	'How big an opportunity is there?',
	'What problems/hurdles are you anticipating?',
	'Who would use your product?',
	'How much does customer acquisition cost?',
	'How will you make money?',
	'How much money could you make per year?',
	'How many users do you have?',
	'What is your user growth rate?',
	'How many users are paying?',
	'How are you meeting customers?',
	'How are you understanding customer needs?',
	'How will you get users?',
	'Who would you hire or how would you add to your team?',
	
	'So what are you working on?',
	'Do you have a demo?',
	'Where is the rocket science here?',
	'How does your product work in more detail?',
	'How is your product different?',
	'What are you going to do next?',
	'What&#39;s new about what you make?',
	'What, exactly, makes you different from existing options?',
	'Who needs what you&#39;re making?',
	'How do you know customers need what you&#39;re making?',
	'Why isn&#39;t someone already doing this?',
	'What obstacles will you face and how will you overcome them?',
	'How will customers and/or users find out about you?',
	'What resistance will they have to trying you and how will you overcome it?',
	'What are the key things about your field that outsiders don&#39;t understand?',
	'What part of your project are you going to build first?',
	'Who is going to be your first paying customer?',
	'If your startup succeeds, what additional areas might you be able to expand into?',
	'Why did you choose this idea?',
	'What have you learned so far from working on your product?',
	'Six months from now, what&#39;s going to be your biggest problem?',
	'Where do new users come from?',
	'What is your growth like?',
	'What&#39;s the conversion rate?',
	'What makes new users try you?',
	'Why do the reluctant users hold back?',
	'What are the top things users want?',
	'What has surprised you about user behaviour?',
	'What&#39;s an impressive thing you have done?',
	'What do you understand about your users?',
	'Why did you pick this idea to work on?',
	'What domain expertise do you have?',
	'Who are your competitors?',
	'Who might become competitors?',
	'Someone just showed us an idea like this right before you guys. I don&#39;t like it. What else do you have?',
	'What competition do you fear most?',
	'What is your distribution strategy?',
	'How did your team meet?',
	'Why did your team get together?',
	'Who in your team does what?',
	'Who is &quot;the boss&quot;?',
	'What will you do if we don&#39;t fund you?',
	'Would you relocate to Silicon Valley?',
	'How do we know your team will stick together?',
	'What else have you created together?',
	'Are you open to changing your idea? ',
	'What systems have you hacked?',
	'Tell us about a tough problem you solved?',
	'In what ways are you resourceful?',
	'Will you reincorporate as a US company?',
	'Will your team stick at this?',
	'Tell us something surprising you have done?',
	'What&#39;s the funniest thing that has happened to you?',
	'What&#39;s the worst thing that has happened?',
	'What&#39;s the biggest mistake you have made?',
	'What is your burn rate?',
	'How long can you go before funding?',
	'What is the next step with the product evolution?',
	'Have you raised funding?',
	'Who would be your next hire?',
	
	'How do you know people want this?',
	'What do you know about this space/product others don&#39;t know?'
	
	"What are you going to do?",
"What does your product do",
"What's the roadmap for the product",
"Could it be used for anything else",
"What will your product not do",
"What is the biggest area of uncertainty",
"Is it possible to get non-devs to to build software",
"How will you get the expertise required to build templates",
"How do you stop this becoming a consultancy business",
"Will people actually be able to build apps that don't all look like 'Stacker apps'",
"What about native mobile",
"How will you turn a new user into a fully on-boarded, committed user",
"How long will it take to go from signup to fully featured product",
"Name companies who could have built their business on Stacker?",
"Why hasn't anyone else done this?",
"How will you get non-technical people to build apps?",
"Can a company grow to a billion dollar company using Stacker?",
"What sort of things can you build on Stacker?",
"Why is now the right time to do this?",
"Why haven't you validated whether people will build on their own?",
"What templates do you currently have?",
"What templates will you add?",
"How do you know each other?",
"Have you done projects together before?",
"What will be your next N hires",
"How big a team do you need to make this a success",
"Do you two have the required skills in (e.g.) Marketing?",
"Where will you be based",
"Why will you not be based in SF?",
"How will you distribute the work?",
"What experience do you guys lack?",
"What mentoring do you need most",
"Which competitor is most similar to you",
"Who is doing this best currently?",
"If you become successful, what's to stop a competitor copying what you're doing and eclipsing you?",
"How are you different from Betty Blocks / Outsystems etc.?",
"Which market category are you competing in?",
"How big is the market?",
"How much of the market do you expect to be able to capture?",
"What are the shortcomings of the ",
"How much money are you making?",
"How much does it cost run a customer?",
"What's your customer LTV?",
"How are you pricing your product?",
"Is your pricing sustainable",
"Are you default-alive?",
"How much will you be making in 5 years?",
"How much profit do you expect to make in Y1,2,3,4...",
"What do you expect to be decent churn",
"What are the top 5 KPIs that will determine the health of your business",
"How much money do you need ",
"How will you make sure you can scale your operation to thousands of customers?",
"How much time will it take to onboard a customer?",
"What's required (operationally) to serve each customer on an ongoing basis?",
"What does the onboarding process look like now, and what will it look like in 1 year?",
"How will you be able to support a growing base of apps?",
"Do people actually need this?",
"Who is it for?",
"Who are your customers?",
"How long do you expect your customers to stay before they churn?",
"When will your customers outgrow your product?",
"Who are your ideal customers?",
"Who are you unideal customers",
"What's your LTV?",
"How many customers have you talked to",
"Where will you find more customers",
"How many have you spoken to?",
"What are the main reasons people don't go with you",
"What are the main reservations that people have",
"When someone comes to Stacker, what's their goal",
"How will you get users?",
"How much will it cost to acquire users?",
"Does your customer acquisition strategy scale?",
"What are your projected user numbers for month #3, 6, 12, 24, 48",
"How fast do you expect to grow",
"Why don't you have more customers now",
"Is there a limit to the number of customers you could reach",
"Who will be hardest for you to reach",
"What portion of the market will you target first",
"What if the market turns out to be harder to get than you expect",
"What external factors could cause you problems going to market",
"What will your CAC be?",
"What is your stack?",
"How scalable is this?",
"How will you manage to run a mission critical service with little money?",
"What are the theoretical limits of your platform?",
"Do you have any reliance on third party service",
"Where are the security risks in your model?",
"Does your software infringe on patents?",
"Won't this get to a point where people outgrow it?",
"How developers be able to work with your platform",
"How will you be able to continue to develop the platform without ruining people's existing apps",
"What are your exit strategies",
"Who are potential acquirers",
"What could cause this to fail",
"What milestones do you need to hit in order to raise future fundraising",
"What are you going to work on during these three months",
];

// Tips
var tips = [
	"I'm a boss and Sam's a little nerd",
	'Try to have quick and concise answers.',
	'Try to answer in 2 to 3 sentences.',
	'Answer like you would in a conversation, this is not a presentation.',
	'When talking to PG and the other YC partners, be substantive, and get straight to the point.',
	'DO NOT BEAT AROUND THE BUSH. Do not hem and haw. "Uhm"s and "uh"s don&#39;t lend an aura of intelligence.',
	'Use precise and concise language. You aren&#39;t pitching a VC that will ask you what your "secret sauce" is.',
	'He talks quickly, and so do the other YC partners. Try to match their tempo (as you should when talking to anyone).'
];
